version: "3.8"
services:

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg!password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/redis/data

volumes:
  redis-data:
  postgres-data: